INSERT INTO `staffing_managers` (user_id, email_address, password, first_name, last_name) VALUES 
(1,'john.doe@example.com','pass','john','doe'),
(2,'jane.doe@example.com','pass','jane','doe'),
(3,'will.smith@example.com','pass','will','smith'),
(4,'charlie.brown@example.com','pass','charlie','brown'),
(5,'debbie.white@example.com','pass','debbie','white'),
(6,'bob.smith@example.com','pass','bob','smith'),
(7,'emily.clark@example.com','pass','emily','clark'),
(8,'fred.jones@example.com','pass','fred','jones'),
(9,'sarah.jane@example.com','pass','sarah','jane');

INSERT INTO `roles` (role_id, client, department, duration, grade_required, job_description, location, role_name, security_clearance_required, staffing_manager_email_address, start_date, version) VALUES 
(152, 'John Lewis', 'ENGAGEMENT_MANAGEMENT', 'THREE_MONTHS', 'GRADE_4', 'As the engagement manager for the Red Team, you will be responsible for maintaining strong relationships with stakeholders and clients, ensuring successful delivery of projects. The role involves coordinating activities, communicating with stakeholders, and ensuring that client needs are met on time and to a high standard. Key responsibilities include monitoring project progress, identifying and resolving issues, and ensuring deadlines and quality standards are met. \n\nOn site requirements - client site once a month and hybrid. \n\nStrong communication, organisation, and problem-solving skills are essential!', 'London', 'Engagement Manager', 'No', 'will.smith@example.com', '2026-04-30', 10),
(202, 'McDonalds', 'DIGITAL_EXPERIENCE', 'NINE_MONTHS', 'GRADE_3', 'You will be responsible for creating user-friendly and intuitive digital experiences for the client. The role involves understanding user needs, designing interfaces, and improving the usability and accessibility of a system. A typical day involves research, creating wireframes and prototypes, and work closely with developers to ensure the final product meets user expectations and accessibility needs.\n\nOn site requirements - hybrid, monthly workshops.\n\nPreferable experience in frontend development or user centric experience.', 'Birmingham', 'UX Designer', 'No', 'jane.doe@example.com', '2026-05-11', 3),
(203, 'McDonalds', 'DIGITAL_EXPERIENCE', 'NINE_MONTHS', 'GRADE_7', 'You will be responsible for creating user-friendly and intuitive digital experiences for the client. The role involves understanding user needs, designing interfaces, and improving the usability and accessibility of a system. A typical day involves research, creating wireframes and prototypes, and working closely with client developers to ensure the final product meets user expectations and accessibility needs.\n\nOn site requirements - hybrid, monthly workshops.\n\n', 'Birmingham', 'UX Designer', 'No', 'jane.doe@example.com', '2026-05-11', 2),
(205, 'HMRC', 'AGILE_DELIVERY', 'TWELVE_MONTHS', 'GRADE_5', 'You will be responsible for identifying business needs and translating them into technical requirements. The role involves gathering and analysing requirements, working closely with stakeholders, and ensuring that solutions align with business objectives. You will help to bridge the gap between users and developers to ensure systems meet user needs and deliver value. \n\nOn site requirements - hybrid, two days in client office per week.', 'Newcastle', 'Business Analyst', 'Yes', 'john.doe@example.com', '2026-06-17', 2),
(252, 'Anglian Water', 'DIGITAL_EXPERIENCE', 'TWELVE_MONTHS', 'GRADE_8', 'As a UX Researcher Lead you will oversee user research activities and ensuring insights are effectively used to improve product design. The role involves planning and guiding research strategies, managing research activities, usability testing and mentoring team members. You will work closely with designers, developers, and stakeholders to ensure products are user-centred and aligned with user needs and requirements. \n\nOn site requirements - once a month in client office, hybrid.', 'Manchester', 'UX Researcher Lead', 'No', 'jane.doe@example.com', '2026-06-01', 3),
(255, 'Scottish Water', 'ARCHITECTURE', 'NINE_MONTHS', 'GRADE_9', 'As a Senior Solutions Architect you are responsible for designing and overseeing the implementation of complex technical solutions that meet business requirements. The role involves defining system architecture, ensuring scalability, security, and performance, and guiding development teams throughout the project lifecycle. Collaboration with stakeholders is essential to align technical solutions with business goals and provide strategic technical leadership. \n\nOn site requirements - client site, hybrid.', 'Birmingham', 'Solutions Architect', 'No', 'charlie.brown@example.com', '2026-05-25', 2),
(302, 'Met Police', 'BUSINESS_OPERATIONS', 'NINE_MONTHS', 'GRADE_6', 'As a Business Operations Partner you will be responsible for supporting and improving business processes to ensure efficient and effective operations. The role involves working with different teams to identify areas for improvement, analysing performance, and implementing solutions that align with business goals. Business Operations Partners help optimise workflows, support decision-making, and contribute to overall organisational success.', 'Telford', 'Business Operations Partner', 'No', 'debbie.white@example.com', '2026-05-25', 3),
(352, 'HMRC', 'PLATFORM_ENGINEERING', 'TWELVE_MONTHS', 'GRADE_5', 'As a DevOps Engineer you will be responsible for automating and improving the development and deployment processes of software systems. The role involves managing infrastructure, implementing CI/CD pipelines, and ensuring system reliability, scalability, and performance. As a DevOps Engineer you will work closely with development and operations teams to streamline workflows and enable faster, more efficient delivery of applications for the client. \n\nOn site requirements - hybrid, two days in client office.', 'Bristol', 'DevOps Engineer', 'Yes', 'bob.smith@example.com', '2026-07-13', 1),
(364, 'John Lewis', 'ENGAGEMENT_MANAGEMENT', 'THREE_MONTHS', 'GRADE_4', 'As the engagement manager for the Red Team, you will be responsible for maintaining strong relationships with stakeholders and clients, ensuring successful delivery of projects. The role involves coordinating activities, communicating with stakeholders, and ensuring that client needs are met on time and to a high standard. Key responsibilities include monitoring project progress, identifying and resolving issues, and ensuring deadlines and quality standards are met. \n\nOn site requirements - client site once a month and hybrid. \n\nStrong communication, organisation, and problem-solving skills are essential!', 'London', 'Engagement Manager', 'No', 'will.smith@example.com', '2026-04-30', 1),
(365, 'McDonalds', 'DIGITAL_EXPERIENCE', 'NINE_MONTHS', 'GRADE_3', 'You will be responsible for creating user-friendly and intuitive digital experiences for the client. The role involves understanding user needs, designing interfaces, and improving the usability and accessibility of a system. A typical day involves research, creating wireframes and prototypes, and work closely with developers to ensure the final product meets user expectations and accessibility needs.\n\nOn site requirements - hybrid, monthly workshops.\n\nPreferable experience in frontend development or user centric experience.', 'Birmingham', 'UX Designer', 'No', 'jane.doe@example.com', '2026-05-11', 3),
(367, 'McDonalds', 'DIGITAL_EXPERIENCE', 'NINE_MONTHS', 'GRADE_7', 'You will be responsible for creating user-friendly and intuitive digital experiences for the client. The role involves understanding user needs, designing interfaces, and improving the usability and accessibility of a system. A typical day involves research, creating wireframes and prototypes, and working closely with client developers to ensure the final product meets user expectations and accessibility needs.\n\nOn site requirements - hybrid, monthly workshops.\n\n', 'Birmingham', 'UX Designer', 'No', 'jane.doe@example.com', '2026-05-11', 2),
(389, 'HMRC', 'AGILE_DELIVERY', 'TWELVE_MONTHS', 'GRADE_5', 'You will be responsible for identifying business needs and translating them into technical requirements. The role involves gathering and analysing requirements, working closely with stakeholders, and ensuring that solutions align with business objectives. You will help to bridge the gap between users and developers to ensure systems meet user needs and deliver value. \n\nOn site requirements - hybrid, two days in client office per week.', 'Newcastle', 'Business Analyst', 'Yes', 'john.doe@example.com', '2026-06-17', 2),
(391, 'Anglian Water', 'DIGITAL_EXPERIENCE', 'TWELVE_MONTHS', 'GRADE_8', 'As a UX Researcher Lead you will oversee user research activities and ensuring insights are effectively used to improve product design. The role involves planning and guiding research strategies, managing research activities, usability testing and mentoring team members. You will work closely with designers, developers, and stakeholders to ensure products are user-centred and aligned with user needs and requirements. \n\nOn site requirements - once a month in client office, hybrid.', 'Manchester', 'UX Researcher Lead', 'No', 'jane.doe@example.com', '2026-06-01', 3)